name: 构建

on:
  push:
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builder_matrix:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10.11'
          architecture: ${{ matrix.arch }}
      - name: Run Windows build
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onefile --noconsole --icon=icon.ico main.py

      - name: Compress GUI contents
        run: |
          copy *.png ./dist/
          copy *.ico ./dist/
          Compress-Archive -Path ./dist/* -DestinationPath gui_contents-${{ matrix.os }}-${{ matrix.arch }}.zip

      - name: Upload
        uses: actions/upload-artifact@v4.4.2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: .\*.zip

      - name: Upload assets to GitHub Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v1
        with:
          files: gui_contents-${{ matrix.os }}-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
